### ISSUE TITLE
Request for experimental details - how many synthetic samples per original sample?

### ISSUE THREAD

**Issue by akhileshgotmare** [varinf/TransformersDataAugmentation#2]
Hi Authors! 

I came across your paper and think it's a great contribution! I have a few questions on the experiments, and would appreciate if you could clarify -

Extrinsic evaluation: 

1. Could you share how you combine (in what ratios) the synthetic and original training sets for the results in Table 4? For instance, for GPT2_context you mention in Section 2.1.2 that the prompt is `y_i SEP w_1 w_2 .. w_k`, and you use nucleus sampling. How many samples do you use for augmentation? Also, since the finetuning set is so small (61 samples or 1% of SST-2), wouldn't these models just re-create the original sequences? Did you face/have to bypass this issue? 

2. What is the base classifier architecture used in extrinsic evaluation to which you feed the augmented set?

3. During training of this base classifier do you randomly sample examples from the augmented set or are we required to ensure some ratio of pure and synthetic samples?

4. Does your c-BERT baseline in row 3 of Table 4 use the 10x generation and selection based on model confidence score as done in the original paper (that may lead to unfair comparison with other methods)?

Intrinsic evaluation:

4. In 3.3.1 you mention that the best classifier is selected based on the performance on the dev partition - does this partition refer to the set of 10 samples from the dev set of a single run? 

also, finally, any estimates on when you could release your implementation here? :)

**Comment by akhileshgotmare** [comment]
Also, you mention SST-2 training set size = 6229 in Table 2. SST-2 is listed at other places with different sizes eg. GLUE benchmark that uses SST-2 claims the training set size to be 67k. Could you help me with this confusion? 

Studies on low resource settings could probably stick with number of samples per class as a measure of scarcity instead of fractions/percentages of the training data.

**Comment by varunentropy** [comment]
Hi,

Extrinsic evaluation:
1. In all experiments, we use 1:1 augmentation ratio i.e. generate one synthetic example for a given example. So in augmentation setting, we have twice the data than no augmentation baseline. 
1.1 since the finetuning set is so small (61 samples or 1% of SST-2), wouldn't these models just re-create the original sequences? -> It doesn't lead to 100% copy pasting, most of the generated sentences are not in the training dataset. Usually, the generated data differ slightly (one word replaced) from the original data. Fine-tuning converges pretty quickly (~3 epochs) so it's less likely to overfit. 
 
2. We use "bert-base-uncased” as a classifier for all experiments (no aug, augmentation)
3. Same as the 1 
4. We don't use any kind of filtering based on model confidence. We are simply generating one example for a given example. Generating more data with model confidence filtering should improve scores across the board but it will make evaluation much harder.

Intrinsic evaluation: We use full dev data for model selection in 3.3.1.

I will check the SST-2 dataset details and will get back to you. Regrading code, I can't release it until we have approval from Amazon legal team, we are making progress there so it should be released in next 15 days or so.   

We are working on an extended version of this paper to use N examples across all datasets instead of N% to make it consistent with low-resource setting.

**Comment by akhileshgotmare** [comment]
Thanks for the clarification! 

Can you share the url/source for the SST-2 dataset you are using? The one that is part of the GLUE benchmark (https://openreview.net/pdf?id=rJ4km2R5t7 - Table 1) seems to have 67k training samples if downloaded as per these instructions on huggingface's transformers library - `https://github.com/huggingface/transformers/blob/master/utils/download_glue_data.py`.

**Comment by akhileshgotmare** [comment]
Few follow-up clarification requests - 
 
5. In table 4, how many epochs is the bert-base-uncased model trained for? If it's trained for say N epochs, do you only use the 10 dev samples to select a checkpoint? or is the last checkpoint used for evaluation?

**Comment by varunentropy** [comment]
SST-2 data source: We used Conditional BERT (CBERT) author's data from https://github.com/1024er/cbert_aug/tree/crayon/datasets/stsa.binary

5. All model selection (classifier, augmentation model finetuning) are done on the basis of dev set performance.

**Comment by varunentropy** [comment]
FYI: We open sourced the code. Closing this issue.
